### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by buggymcbugfix** [rpearce/robertwpearce.com#36]
Hey, I love your blog setup. May I reuse your code? I'd be happy to attribute.

**Comment by rpearce** [comment]
That's really kind of you to ask. I'll add a LICENSE ASAP

**Comment by rpearce** [comment]
I'm also going to see about pulling some of these things out into hakyll-oriented plugin packages. Stay tuned!

**Comment by buggymcbugfix** [comment]
Great, thank you!
